# Generated by Django 5.1.5 on 2025-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='tokennum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
