# Generated by Django 5.1.5 on 2025-08-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondimage',
            name='bondholdername',
        ),
    ]
