# Generated by Django 5.1.5 on 2025-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykyc',
            name='bondimagetype',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('xerox', 'Xerox')], max_length=10, null=True, verbose_name='Bond Image Type'),
        ),
    ]
