# Generated by Django 5.1.5 on 2025-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bondimage_bondholdername'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='bondholdername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
