# Generated by Django 5.1.5 on 2025-08-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mykyc_bondimagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='contactSH',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='investmentamt',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='nameSH',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='profession',
        ),
    ]
