# Generated by Django 5.1.5 on 2025-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mykyc_address_remove_mykyc_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='bondimage',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='bondimagetype',
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='aadhar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='depositormobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
