# Generated by Django 5.1.5 on 2025-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bondimage_bondimagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondimage',
            name='bondimagetype',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('xerox', 'Xerox')], max_length=50, null=True),
        ),
    ]
