# Generated by Django 5.1.5 on 2025-09-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bondimage_bondholdername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='projectname',
        ),
    ]
