# Generated by Django 5.1.5 on 2025-08-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_mykyc_bondimage_remove_mykyc_bondimagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='membershiptype',
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='aadhar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='aadhar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='passportphoto',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/passport/'),
        ),
    ]
