# Generated by Django 5.1.5 on 2025-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bondimage_bondimagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mykyc',
            name='agentmailid',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
