# Generated by Django 5.1.5 on 2025-09-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_mykyc_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='balanceamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bondimage',
            name='refundamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
