# Generated by Django 5.1.5 on 2025-09-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bondimage_remarks_mykyc_agentmailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='passportphoto',
        ),
    ]
