# Generated by Django 5.1.5 on 2025-10-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bondimage_agentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='agentaddress',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='agentmailid',
        ),
    ]
