# Generated by Django 5.1.5 on 2025-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetailsnew',
            name='contactSH',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycdetailsnew',
            name='investmentamt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdetailsnew',
            name='nameSH',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycdetailsnew',
            name='passportphoto',
            field=models.ImageField(default='', upload_to='kyc/passport_photo/'),
        ),
    ]
