# Generated by Django 5.1.5 on 2025-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kycdetailsnew_contactsh_kycdetailsnew_investmentamt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetailsnew',
            name='passportphoto',
            field=models.ImageField(upload_to='kyc/passport_photo/'),
        ),
    ]
