# Generated by Django 4.2.9 on 2025-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_jwt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_user',
            field=models.BooleanField(default=False),
        ),
    ]
