# Generated by Django 5.1.5 on 2025-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_kycdetailsnew_passportphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetailsnew',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kycdetailsnew',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='kycdetailsnew',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='kycdetailsnew',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
