# Generated by Django 4.2.9 on 2025-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_main_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_image', models.ImageField(upload_to='kyc/aadhar/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_image', models.ImageField(upload_to='kyc/pan/')),
            ],
        ),
    ]
