# Generated by Django 5.1.5 on 2025-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_kycdetailsnew_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetailsnew',
            name='bond',
            field=models.ImageField(default='', upload_to='kyc/passport_photo/'),
        ),
    ]
