# Generated by Django 4.2.9 on 2025-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kycdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
