# Generated by Django 5.1.5 on 2025-06-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kycdetailsnew_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetailsnew',
            name='bond',
            field=models.ImageField(upload_to='kyc/passport_photo/'),
        ),
    ]
