# Generated by Django 4.2.9 on 2025-06-10 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kycdetails_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
