# Generated by Django 5.1.5 on 2025-06-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bondimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BondImage',
        ),
    ]
