# Generated by Django 5.1.5 on 2025-06-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_bondimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kyc/bonds/')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='app.kycdetailsnew')),
            ],
        ),
    ]
