# Generated by Django 5.1.5 on 2025-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bondimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_mainuser',
            field=models.BooleanField(default=False),
        ),
    ]
