# Generated by Django 5.1.5 on 2025-06-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_sub_mainuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetailsnew',
            name='bond',
        ),
    ]
