# Generated by Django 5.1.5 on 2025-06-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
