# Generated by Django 5.1.5 on 2025-06-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_user_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passportphoto', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
