# Generated by Django 5.1.5 on 2025-06-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_subuserkyc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubUserKYC',
        ),
    ]
