# Generated by Django 5.1.5 on 2025-06-25 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_subuserkyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDetailsTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('fathername', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=14)),
                ('aadhar_image', models.ImageField(upload_to='aadhar_images/')),
                ('pan_image', models.ImageField(upload_to='pan_images/')),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('contactSH', models.CharField(max_length=100)),
                ('nameSH', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passportphoto', models.ImageField(upload_to='passport_photos/')),
                ('bonds', models.ManyToManyField(blank=True, to='app.bondimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycDetailsTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('fathername', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=14)),
                ('aadhar_image', models.ImageField(upload_to='aadhar_images/')),
                ('pan_image', models.ImageField(upload_to='pan_images/')),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('contactSH', models.CharField(max_length=100)),
                ('nameSH', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passportphoto', models.ImageField(upload_to='passport_photos/')),
                ('bonds', models.ManyToManyField(blank=True, to='app.bondimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
