# Generated by Django 5.1.5 on 2025-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_kycdetailstable1_kycdetailstable2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetailstable2',
            name='bonds',
        ),
        migrations.AddField(
            model_name='kycdetailstable2',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycdetailstable2',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kycdetailstable2',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kycdetailstable2',
            name='investmentamt',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='KycDetailsTable1',
        ),
    ]
