# Generated by Django 5.1.5 on 2025-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_kycdetailstable2_bonds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KycDetailsTable2',
        ),
    ]
