# Generated by Django 5.1.5 on 2025-06-26 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_kycdetailstable2'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetailsnew',
            name='data_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
