# Generated by Django 5.1.5 on 2025-06-26 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_kycdetailsnew_data_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetailsnew',
            name='data_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
