# Generated by Django 5.1.5 on 2025-06-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_kycdetailsnew_data_for_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdetailsnew',
            old_name='data_for_user',
            new_name='created_by',
        ),
    ]
