# Generated by Django 5.1.5 on 2025-06-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_data_for_user_kycdetailsnew_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetailsnew',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
