# Generated by Django 5.1.5 on 2025-07-01 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_user_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondimage',
            name='kyc',
        ),
        migrations.AlterField(
            model_name='bondimage',
            name='image',
            field=models.ImageField(upload_to='bond_images/'),
        ),
        migrations.CreateModel(
            name='MyKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('fathername', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='aadhar_front/')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='aadhar_back/')),
                ('profession', models.CharField(max_length=100)),
                ('contactSH', models.CharField(max_length=100)),
                ('nameSH', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passportphoto', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bondimage',
            name='my_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='app.mykyc'),
        ),
        migrations.CreateModel(
            name='SubKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('fathername', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='sub_aadhar_front/')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='sub_aadhar_back/')),
                ('profession', models.CharField(max_length=100)),
                ('contactSH', models.CharField(max_length=100)),
                ('nameSH', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passportphoto', models.ImageField(blank=True, null=True, upload_to='sub_passport_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kycs_created', to=settings.AUTH_USER_MODEL)),
                ('data_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kycs_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bondimage',
            name='sub_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='app.subkyc'),
        ),
        migrations.DeleteModel(
            name='KycDetailsNew',
        ),
    ]
