# Generated by Django 5.1.5 on 2025-07-01 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_bondimage_kyc_alter_bondimage_image_mykyc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subkyc',
            name='data_for_user',
        ),
        migrations.AddField(
            model_name='mykyc',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mykyc',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='my_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subkyc',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='contactSH',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_my_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='investmentamt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='nameSH',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='passportphoto',
            field=models.ImageField(blank=True, null=True, upload_to='passport/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
