# Generated by Django 5.1.5 on 2025-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_mykyc_created_at_remove_subkyc_data_for_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondimage',
            name='image',
            field=models.ImageField(upload_to='bonds/'),
        ),
    ]
