# Generated by Django 5.1.5 on 2025-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_bondimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subkyc',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
